DROP TABLE IF EXISTS PHONES;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS NAMES;

CREATE TABLE NAMES (
                   ID BIGINT GENERATED ALWAYS AS IDENTITY,
                   FIRST VARCHAR(250) NOT NULL,
                   MIDDLE VARCHAR(250) NOT NULL,
                   LAST VARCHAR(250) NOT NULL,
                   EMAIL VARCHAR(250) UNIQUE NOT NULL,
                   CONSTRAINT PK_Name PRIMARY KEY (ID)
);

CREATE TABLE PHONES (
                   ID BIGINT GENERATED ALWAYS AS IDENTITY,
                   NUMBER VARCHAR(20) NOT NULL,
                   TYPE VARCHAR(6) NOT NULL,
                   NAME_ID INT,
                   CONSTRAINT FK_NAMES_PHONE_NUMBER_ID FOREIGN KEY (NAME_ID) REFERENCES Names (ID),
                   CONSTRAINT FK_NAMES_PHONE_UNIQUE_ROW UNIQUE (TYPE, NAME_ID)

);

CREATE TABLE ADDRESS (
                   ID BIGINT GENERATED ALWAYS AS IDENTITY,
                   STREET VARCHAR(250) NOT NULL,
                   CITY VARCHAR(250) NOT NULL,
                   STATE VARCHAR(250) NOT NULL,
                   ZIP VARCHAR(11) NOT NULL,
                   NAME_ID INT,
                   CONSTRAINT FK_NAMES_ADDRESS_ID FOREIGN KEY (NAME_ID) REFERENCES Names (ID)
);